-- alatech.activity_day_of_first_monday definition

CREATE TABLE `activity_day_of_first_monday` (
  `user_id` int(64) NOT NULL,
  `week_num` int(8) NOT NULL,
  `day_num` int(8) NOT NULL,
  `start_time` varchar(64) DEFAULT NULL,
  `end_time` varchar(64) DEFAULT NULL,
  `type` varchar(64) NOT NULL,
  `total_activities` int(16) DEFAULT NULL,
  `total_second` varchar(16) DEFAULT NULL,
  `total_distance_meters` float DEFAULT NULL,
  `elev_gain` float DEFAULT NULL,
  `elev_loss` float DEFAULT NULL,
  `calories` float DEFAULT NULL,
  `avg_heart_rate_bpm` float DEFAULT NULL,
  `avg_max_heart_rate_bpm` float DEFAULT NULL,
  `avg_speed` float DEFAULT NULL,
  `avg_max_speed` float DEFAULT NULL,
  `avg_cadence` float DEFAULT NULL,
  `avg_max_cadence` float DEFAULT NULL,
  `cycle_avg_watt` float DEFAULT NULL,
  `avg_cycle_max_watt` float DEFAULT NULL,
  `total_weight_kg` float DEFAULT NULL,
  `total_reps` int(8) DEFAULT NULL,
  `year_num` int(8) NOT NULL,
  `privacy_me` varchar(16) NOT NULL DEFAULT 'true',
  `privacy_friend` varchar(16) NOT NULL DEFAULT 'false',
  `privacy_group` varchar(16) NOT NULL DEFAULT 'false',
  `privacy_coach` varchar(16) NOT NULL DEFAULT 'false',
  `privacy_any` varchar(16) NOT NULL DEFAULT 'false',
  `gmt_start_time` varchar(64) DEFAULT NULL,
  `gmt_end_time` varchar(64) DEFAULT NULL,
  `avg_climb_incline_ratio` float DEFAULT NULL,
  `max_100m_incline_ratio` float DEFAULT NULL,
  `min_100m_incline_ratio` float DEFAULT NULL,
  `total_hr_zone0_second` int(16) DEFAULT NULL,
  `total_hr_zone1_second` int(16) DEFAULT NULL,
  `total_hr_zone2_second` int(16) DEFAULT NULL,
  `total_hr_zone3_second` int(16) DEFAULT NULL,
  `total_hr_zone4_second` int(16) DEFAULT NULL,
  `total_hr_zone5_second` int(16) DEFAULT NULL,
  `total_elev_gain_second` int(16) DEFAULT NULL,
  `total_elev_loss_second` int(16) DEFAULT NULL,
  `avg_swolf` int(16) DEFAULT NULL,
  `best_swolf` int(16) DEFAULT NULL,
  `rowing_avg_watt` float DEFAULT NULL,
  `rowing_max_watt` float DEFAULT NULL,
  `total_plus_g_force_x` float DEFAULT NULL,
  `total_plus_g_force_y` float DEFAULT NULL,
  `total_plus_g_force_z` float DEFAULT NULL,
  `total_minus_g_force_x` float DEFAULT NULL,
  `total_minus_g_force_y` float DEFAULT NULL,
  `total_minus_g_force_z` float DEFAULT NULL,
  `max_g_force_x` float DEFAULT NULL,
  `max_g_force_y` float DEFAULT NULL,
  `max_g_force_z` float DEFAULT NULL,
  `mini_g_force_x` float DEFAULT NULL,
  `mini_g_force_y` float DEFAULT NULL,
  `mini_g_force_z` float DEFAULT NULL,
  `total_ftp_zone0_second` int(16) DEFAULT NULL,
  `total_ftp_zone1_second` int(16) DEFAULT NULL,
  `total_ftp_zone2_second` int(16) DEFAULT NULL,
  `total_ftp_zone3_second` int(16) DEFAULT NULL,
  `total_ftp_zone4_second` int(16) DEFAULT NULL,
  `total_ftp_zone5_second` int(16) DEFAULT NULL,
  `total_ftp_zone6_second` int(16) DEFAULT NULL,
  `max_heart_rate_bpm` int(8) DEFAULT NULL,
  `max_speed` float DEFAULT NULL,
  `max_cadence` float DEFAULT NULL,
  `cycle_max_watt` float DEFAULT NULL,
  `avg_estimate_ftp` float DEFAULT NULL,
  `total_swing_count` int(64) DEFAULT NULL,
  `total_forehand_swing_count` int(32) DEFAULT NULL,
  `total_backhand_swing_count` int(32) DEFAULT NULL,
  `avg_swing_speed` float DEFAULT NULL,
  `max_swing_speed` float DEFAULT NULL,
  `personalized_activity_intelligence` int(16) DEFAULT NULL,
  `total_activity_second` varchar(16) DEFAULT NULL,
  `total_feedback_energy` double DEFAULT NULL,
  PRIMARY KEY (`user_id`,`year_num`,`week_num`,`day_num`,`type`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;