-- alatech.file_info definition

CREATE TABLE `file_info` (
  `header_id` int(64) DEFAULT NULL,
  `user_id` int(64) DEFAULT NULL,
  `group_id` int(32) DEFAULT NULL,
  `device_id` int(64) DEFAULT NULL,
  `type` enum('1','2','3','4','5','6','7','8','9','10','100','101') NOT NULL,
  `file_id` mediumint(9) NOT NULL AUTO_INCREMENT,
  `creation_date` varchar(64) DEFAULT NULL,
  `creation_unix_timestamp` varchar(16) DEFAULT NULL,
  `creation_time_zone` varchar(16) DEFAULT NULL,
  `create_from` varchar(32) DEFAULT NULL,
  `country_region` varchar(16) DEFAULT NULL,
  `language` varchar(16) DEFAULT NULL,
  `complex_next_id` varchar(64) DEFAULT NULL,
  `sync_date` varchar(64) DEFAULT NULL,
  `display_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `author` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `edit_date` varchar(64) DEFAULT NULL,
  `equipment_sn` varchar(128) DEFAULT NULL,
  `equipment_fw_name` varchar(16) DEFAULT NULL,
  `equipment_fw_code` varchar(8) DEFAULT NULL,
  `equipment_hw_name` varchar(16) DEFAULT NULL,
  `equipment_hw_code` varchar(8) DEFAULT NULL,
  `example_format` varchar(256) DEFAULT NULL,
  `company` varchar(128) DEFAULT NULL,
  `ala_format_version_name` varchar(8) DEFAULT NULL,
  `ala_format_version_code` varchar(1) DEFAULT NULL,
  `location` varchar(256) DEFAULT NULL,
  `photo` mediumtext CHARACTER SET ascii,
  `video` varchar(256) DEFAULT NULL,
  `tag` varchar(256) DEFAULT NULL,
  `tagman` varchar(256) DEFAULT NULL,
  `note` varchar(512) DEFAULT NULL,
  `privacy` varchar(64) NOT NULL DEFAULT '1',
  `teacher` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `class` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `brand` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `v1_file_name` varchar(64) DEFAULT NULL,
  `v1_md5_unicode` varchar(64) DEFAULT NULL,
  `total_file_index` mediumint(9) DEFAULT NULL,
  `privacy_me` varchar(16) NOT NULL DEFAULT 'true',
  `privacy_friend` varchar(16) NOT NULL DEFAULT 'false',
  `privacy_group` varchar(16) NOT NULL DEFAULT 'false',
  `privacy_coach` varchar(16) NOT NULL DEFAULT 'false',
  `privacy_any` varchar(16) NOT NULL DEFAULT 'false',
  `gmt_creation_date` varchar(64) DEFAULT NULL,
  `gmt_sync_date` varchar(64) DEFAULT NULL,
  `gmt_edit_date` varchar(64) DEFAULT NULL,
  `upload_raw_file_name` longtext,
  `branch` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cloud_run_map_id` varchar(512) DEFAULT NULL,
  `complex_id` varchar(64) DEFAULT NULL,
  `file_group_id` mediumint(9) DEFAULT NULL,
  `matched_plan_id` mediumint(9) DEFAULT NULL,
  UNIQUE KEY `type` (`type`,`file_id`),
  KEY `index_key` (`user_id`,`type`,`creation_date`) USING BTREE
) ENGINE=MyISAM DEFAULT CHARSET=utf8;